### ISSUE TITLE
Gigabyte F20b BIOS Update Initial Display Output

### ISSUE THREAD

**Issue by azhinu** [augstb/Hackintosh-Intel-i7-10700k-Gigabyte-Z490-Vision-G#1]
Actually you don't need to enable CSM to set IGFX as initial display output. You just need to set CSM enabled then change Initial display output preference and then disable CSM.

**Comment by augstb** [comment]
Thank you for the little trick, I updated the README in af2257a0088c1eca10f7ef653624293d9b0e1dfe. Hopefully this will fix sleep issues with F20b BIOS version.
