### ISSUE TITLE
What do you recommend?

### ISSUE THREAD

**Issue by rodrigobaroni** [augstb/Hackintosh-Intel-i7-10700k-Gigabyte-Z490-Vision-G#3]
If know this is not a issue, but man you help me a lot with this repository

i using the same config with you and my hackintosh works pretty fine

but i on the big sur 11.2.3, my question is about to update

Do you recommend to update directly or make a clean install?

sorry for my bad english, i from Brazil...

Thank You

**Comment by augstb** [comment]
I recently updated to macOS 11.6 without any trouble at all during the installation. Just make sure OpenCore is correctly updated to latest version before to update to reduce the risks.
I recommend to make a backup first, and trying to update like a real mac. If you have problems after the update and you can't get it to work even after working on your EFI folder, try a fresh install. Don't forget that you can restore from a hard drive when fresh installing so all your personal work will be recovered (so don't format). That can be very useful even when you don't have any backup.
